/**
 * events.js
 * Centralized event names for communication between JS and .NET.
 */

export const EVENTS = {
    // Outgoing
    READY: "READY",
    SEND_MESSAGE: 'SEND_MESSAGE',
    INIT_STATE: 'INIT_STATE',
    SELECT_PROVIDER: 'SELECT_PROVIDER',
    SELECT_MODEL: 'SELECT_MODEL',
    CANCEL_GENERATION: 'CANCEL_GENERATION',
    UPDATE_SETTINGS: "UPDATE_SETTINGS",
    UI_ERROR: "UI_ERROR",
    SELECT_CHAT: "SELECT_CHAT",
    SELECT_GROUP: "SELECT_GROUP",
    NEW_CHAT: "NEW_CHAT",
    DELETE_CHAT: "DELETE_CHAT",
    NEW_GROUP: "NEW_GROUP",
    UPDATE_GROUP: "UPDATE_GROUP",
    DELETE_GROUP: "DELETE_GROUP",
    OPEN_EXTERNAL_LINK: "OPEN_EXTERNAL_LINK",
    REFRESH_PROVIDER_MODELS: "REFRESH_PROVIDER_MODELS",
    SAVE_SETTINGS: "SAVE_SETTINGS",

    // Incoming
    INIT_DATA: 'INIT_DATA',
    AI_RESPONSE: 'AI_RESPONSE',
    STREAM_CHUNK: 'STREAM_CHUNK',
    STATUS_CHANGED: 'STATUS_CHANGED',
    ERROR: 'ERROR',
    SET_LOADING: 'SET_LOADING',
    SELECT_MODEL_APPROVED: 'SELECT_MODEL_APPROVED',
    SELECT_CHAT_APPROVED: 'SELECT_CHAT_APPROVED',
    SELECT_GROUP_APPROVED: 'SELECT_GROUP_APPROVED',
    CHAT_TITLE_CHANGED: "CHAT_TITLE_CHANGED",
    ACTIVE_DOCUMENT_CHANGED: "ACTIVE_DOCUMENT_CHANGED",
    CHANGE_MODEL_SETTING_APPROVED:"CHANGE_MODEL_SETTING_APPROVED",
    CHANGE_MODEL_SETTING_REJECTED: "CHANGE_MODEL_SETTING_REJECTED",
    PROVIDER_MODELS_REFRESHED: "PROVIDER_MODELS_REFRESHED",
    SETTINGS_SAVED: "SETTINGS_SAVED",
};


export const CUSTOME_EVENTS = {
   CLOSE_ALL_DROPDOWNS : "ui:close-all-dropdowns"
}