/**
 * events.js
 * Centralized event names for communication between JS and .NET.
 */

export const EVENTS = {
    // Outgoing
    READY: "READY",
    SEND_MESSAGE: 'SEND_MESSAGE',
    INIT_STATE: 'INIT_STATE',
    SELECT_PROVIDER: 'SELECT_PROVIDER',
    SELECT_MODEL: 'SELECT_MODEL',
    CANCEL_GENERATION: 'CANCEL_GENERATION',
    UPDATE_SETTINGS: "UPDATE_SETTINGS",
    UI_ERROR: "UI_ERROR",
    SELECT_CHAT: "SELECT_CHAT",
    SELECT_GROUP: "SELECT_GROUP",
    NEW_CHAT: "NEW_CHAT",
    UPDATE_CHAT: "UPDATE_CHAT",
    DELETE_CHAT: "DELETE_CHAT",
    NEW_GROUP: "NEW_GROUP",
    UPDATE_GROUP: "UPDATE_GROUP",
    DELETE_GROUP: "DELETE_GROUP",
    OPEN_EXTERNAL_LINK: "OPEN_EXTERNAL_LINK",
    OPEN_REFERENCE_FILE: "OPEN_REFERENCE_FILE",
    REFRESH_PROVIDER_MODELS: "REFRESH_PROVIDER_MODELS",
    SAVE_SETTINGS: "SAVE_SETTINGS",
    SAVE_SOLUTION_INSTRUCTION: "SAVE_SOLUTION_INSTRUCTION",
    REOPEN_CHANGESET_REVIEW: "REOPEN_CHANGESET_REVIEW",
    ASK_USER_ANSWER: "ASK_USER_ANSWER",
    REWIND_CHAT: "REWIND_CHAT",

    // Incoming
    INIT_DATA: 'INIT_DATA',
    AI_RESPONSE: 'AI_RESPONSE',
    STREAM_CHUNK: 'STREAM_CHUNK',
    THINKING_STARTED: 'THINKING_STARTED',
    THINKING_CHUNK: 'THINKING_CHUNK',
    THINKING_COMPLETED: 'THINKING_COMPLETED',
    STATUS_CHANGED: 'STATUS_CHANGED',
    ERROR: 'ERROR',
    SET_LOADING: 'SET_LOADING',
    SELECT_MODEL_APPROVED: 'SELECT_MODEL_APPROVED',
    SELECT_CHAT_APPROVED: 'SELECT_CHAT_APPROVED',
    SELECT_GROUP_APPROVED: 'SELECT_GROUP_APPROVED',
    CHAT_TITLE_CHANGED: "CHAT_TITLE_CHANGED",
    ACTIVE_DOCUMENT_CHANGED: "ACTIVE_DOCUMENT_CHANGED",
    INPUT_LANGUAGE_CHANGED: "INPUT_LANGUAGE_CHANGED",
    CHANGE_MODEL_SETTING_APPROVED:"CHANGE_MODEL_SETTING_APPROVED",
    CHANGE_MODEL_SETTING_REJECTED: "CHANGE_MODEL_SETTING_REJECTED",
    PROVIDER_MODELS_REFRESHED: "PROVIDER_MODELS_REFRESHED",
    SETTINGS_SAVED: "SETTINGS_SAVED",
    SOLUTION_INSTRUCTION_SAVED: "SOLUTION_INSTRUCTION_SAVED",
    CHAT_BLOCKED: "CHAT_BLOCKED",
    CHAT_UNBLOCKED: "CHAT_UNBLOCKED",
    ASK_USER_QUESTION: "ASK_USER_QUESTION",
    REWIND_CHAT_APPROVED: "REWIND_CHAT_APPROVED",
    ADD_SELECTED_CODE_REFERENCE: "ADD_SELECTED_CODE_REFERENCE",
    RUN_DESCRIBE_ON_SELECTION: "RUN_DESCRIBE_ON_SELECTION",
};


export const CUSTOME_EVENTS = {
   CLOSE_ALL_DROPDOWNS : "ui:close-all-dropdowns"
}